wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("search", views.search, name="search_results"),
    path("new_entry", views.new_entry, name="new_page"),
    path("random", views.get_random_entry, name="random_page"),
    path("<str:entry>", views.navigate_to_entry, name="entry"),
    path("edit/<str:entry>", views.edit_entry, name="edit_page"),
    path("delete/<str:entry>", views.delete_entry, name="delete_page")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls", namespace="wiki")),
    path('', include("encyclopedia.urls", namespace="wiki"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
import random

from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.forms import Form, CharField, Textarea
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from . import util

from .util import summarize_entry, get_entry


class NewEntryForm(Form):
    title = CharField(label="Title")
    content = CharField(widget=Textarea, label="Content")


def index(request):
    query = request.GET.get("q")
    if query is not None:
        return search(request, query=query)

    entries = [{"title": e, "summary": summarize_entry(get_entry(e))} for e in util.list_entries()]

    return render(
        request,
        "encyclopedia/index.html", {
            "entries": entries,
            "title": "All Pages"
        }
    )


def navigate_to_entry(request, entry: str):
    content = util.get_entry(title=entry)

    if content is None:
        raise Http404()

    return render(
        request,
        "encyclopedia/entry.html", {
            "entry": entry,
            "content": util.convert_markdown_to_html(content)
        }
    )


def search(request, query: str):
    entries = util.list_entries()
    if query in entries:
        return navigate_to_entry(request, entry=query)

    entries_substring = [entry for entry in entries if query.lower() in entry.lower()]
    entries_substring = [{"title": e, "summary": summarize_entry(get_entry(e))} for e in entries_substring]
    return render(
        request,
        "encyclopedia/index.html", {
            "title": f"Search Results for '{query}'",
            "entries": entries_substring
        }
    )


def new_entry(request):
    if request.method == "POST":

        form = NewEntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            path_save = f'entries/{title}.md'
            if default_storage.exists(path_save):
                return render(request, "encyclopedia/new_entry.html", {
                    "form": form,
                    "message": "Title already exists"
                })
            path_save = default_storage.save(path_save, ContentFile(content))
            assert default_storage.exists(path_save), f"{path_save} is not correctly saved"
            return HttpResponseRedirect(reverse("wiki:index"))

        return render(request, "encyclopedia/new_entry.html", {
            "form": form,
            "message": ""
        })

    return render(request, "encyclopedia/new_entry.html", {
        "form": NewEntryForm(
            initial={
                'title': 'Title',
                'content': 'Content'
            }
        )
    })


def edit_entry(request, entry):
    if request.method == "POST":
        form = NewEntryForm(request.POST)

        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            path_save = f'entries/{title}.md'
            if default_storage.exists(path_save):
                default_storage.delete(path_save)  # Delete to simulate overwriting
            path_save = default_storage.save(path_save, ContentFile(content))
            assert default_storage.exists(path_save), f"{path_save} is not correctly saved"
            return redirect("wiki:entry", entry=entry)

        return render(
            request,
            "encyclopedia/edit_entry.html", {
                "entry": entry,
                "form": form
            }
        )

    content = util.get_entry(title=entry)

    if content is None:
        raise Http404()

    return render(
        request,
        "encyclopedia/edit_entry.html", {
            "entry": entry,
            "form": NewEntryForm(
                initial={
                    'title': entry,
                    'content': content
                }
            )
        })


def delete_entry(request, entry):
    if request.method == "POST":
        path_entry = f'entries/{entry}.md'
        if default_storage.exists(path_entry):
            default_storage.delete(path_entry)
        return redirect('wiki:index')
    return render(request, "encyclopedia/delete_entry.html", {
        "entry": entry
    })


def get_random_entry(request):
    entry = random.choice(util.list_entries())
    return redirect('wiki:entry', entry=entry)

wiki/encyclopedia/templates/encyclopedia/delete_entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Delete {{ entry }}
{% endblock %}

{% block body %}

    <form action="{% url 'wiki:delete_page' entry %}" method="post">
        {% csrf_token %}
        <h2>Are you sure you want to delete this page?</h2>
        <div class="row">
            <input type="submit" value="Yes" class="btn btn-secondary" title="Yes">
            <a href="{% url "wiki:index" %}" class="btn btn-secondary">No</a>
        </div>
    </form>


{% endblock %}

wiki/encyclopedia/templates/encyclopedia/edit_entry.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
    <h1>Edit Entry:</h1>

    <form action="{% url 'wiki:edit_page' entry %}" method="post">
        {% csrf_token %}
        <div class="row">{{ form.title }}</div>
        <div class="row">{{ form.content }}</div>
        <div class="row">
            <input type="submit" class="btn btn-success" title="Save" value="Save">
            <a href="{% url "wiki:index" %}" class="btn btn-secondary">Cancel</a>
        </div>
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ entry }}
{% endblock %}

{% block body %}

    {{ content|safe }}

    <div class="row">
        <a href="{% url "wiki:edit_page" entry %}" class="btn btn-secondary">Edit</a>
        <a href="{% url "wiki:delete_page" entry %}" class="btn btn-danger" id="delete">Delete</a>
    </div>


{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>{{ title }}</h1>

    {% if entries %}
        <table style="width:30%">
            <tr>
                <th>Title</th>
                <th>Summary</th>
            </tr>
            {% for entry in entries %}
                <tr>
                    <td><a href="{% url 'wiki:entry' entry.title %}">{{ entry.title }}</a></td>
                    <td>{{ entry.summary }}</td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        Found no pages
    {% endif %}

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

</head>
<body>
<div class="row">
    <div class="sidebar col-lg-2 col-md-3">
        <h1>Wiki</h1>
        <form>
            <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
        </form>
        <div>
            <a href="{% url 'wiki:index' %}">Home</a>
        </div>
        <div>
            <a href="{% url 'wiki:new_page' %}">Create New Page</a>
        </div>
        <div>
            <a href="{% url 'wiki:random_page' %}">Random Page</a>
        </div>
        {% block nav %}
        {% endblock %}
    </div>
    <div class="main col-lg-10 col-md-9">
        {% block body %}
        {% endblock %}
    </div>
</div>

</body>
</html>

wiki/encyclopedia/templates/encyclopedia/new_entry.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
    <h1>Add Entry:</h1>

    {% if message %}
        <script>
            alert('{{ message }}');
        </script>
    {% endif %}

    <form action="{% url 'wiki:new_page' %}" method="post">
        {% csrf_token %}
        <div class="row">{{ form.title }}</div>
        <div class="row">{{ form.content }}</div>
        <div class="row">
            <input type="submit" class="btn btn-success" title="Save" value="Save">
            <a href="{% url "wiki:index" %}" class="btn btn-secondary">Cancel</a>
        </div>
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/random_entry.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
    <h1>Random Entry:</h1>

    <form action="{% url 'wiki:new_page' %}" method="post">
        {% csrf_token %}
        <div class="row">{{ form.title }}</div>
        <div class="row">{{ form.content }}</div>
        <div class="row">
            <input type="submit" class="btn btn-success" title="Save" value="Save">
            <a href="{% url "wiki:index" %}" class="btn btn-secondary">Cancel</a>
        </div>
    </form>

{% endblock %}